# Site settings
title: stesie's musings
email: stesie@brokenpipe.de
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://stesie.github.io"
twitter_username: stesie23
github_username:  stesie

# Build settings
markdown: kramdown
permalink: pretty

gems:
 - jekyll-paginate

paginate: 5
