# Site settings
title: stesie's musings
email: stesie@brokenpipe.de
description: "This is my personal collection of random musings, related to stuff I am interested in ... that is web-related development (PHP, JavaScript), Software Craftsmanship, Docker, Continuous Integration, ... you name it"
baseurl: ""
url: "http://stesie.github.io"
twitter_username: stesie23
github_username:  stesie

# Build settings
markdown: kramdown
permalink: pretty

gems:
 - jekyll-paginate
 - jekyll-mentions

paginate: 5

jekyll-mentions:
  base_url: https://twitter.com
