baseURL: https://stesie.github.io
languageCode: en-us
title: stesie's musings
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Hello World 👋
    Content: This is my personal collection of random musings, related to stuff I am interested in ... that is web-related development, Software Craft, Cycling ...

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/stesie"
    - name: "codeberg"
      url: "https://codeberg.org/stesie"
    - name: "mastodon"
      url: "https://wue.social/@rolf"
    - name: "rss"
      url: "https://stesie.github.io/feed.xml"
    - name: "strava"
      url: "https://www.strava.com/athletes/53820805"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #   url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Stefan Siegl"
  contact: "stesie@brokenpipe.de"
  feedlinks: true
  mobileMenu: true

  #Google Analytics 4 optional
  env: #production
  #GoogleAnalytics: "G-00000XXXXX"
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
      # section:
      #   - HTML
      #   - RSS
      #   - JSON

outputFormats:
  RSS:
    baseName: feed

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 90
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20


permalinks:
  page:
    pages: :year/:month/:slug/
